### ISSUE TITLE
Clear button clears all entries, including downloading

### ISSUE THREAD

**Issue by xinhangliu** [xinghaixuanwo/download-manager#1]
I think the clear button should only clear entries where the download is completed or failed.

BTW, this is the most elegant download manager I have found so far. Thanks!

**Comment by xinghaixuanwo** [comment]
Thanks, i will fix this in the next version😆

**Comment by xinghaixuanwo** [comment]
> I think the clear button should only clear entries where the download is completed or failed.
> 
> BTW, this is the most elegant download manager I have found so far. Thanks!
